# Generated by Django 3.1 on 2021-04-22 05:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 10 digits allowed.', regex='^\\+?1?\\d{9,10}$')], verbose_name='Phone')),
                ('profile', models.ImageField(upload_to='user_profile%y%m%d')),
                ('is_seeker', models.BooleanField(default=False)),
                ('is_hirer', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='mydocs_resume/', verbose_name='Document')),
                ('bod', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('school_name', models.CharField(max_length=100)),
                ('passing_year', models.DateField()),
                ('percentage', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('user_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campnay_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campany_logo', models.FileField(upload_to='mydocs_resume/', verbose_name='Document')),
                ('location', models.CharField(max_length=300)),
                ('company_name', models.CharField(max_length=100)),
                ('company_year', models.DateField()),
                ('company_site', models.URLField()),
                ('user_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Job_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_cat', models.CharField(choices=[('Graphic Designer', 'Graphic Designer'), ('Engineering Jobs ', 'Engineering Jobs '), ('Mainframe Jobs', 'Mainframe Jobs'), ('Legal Jobs', 'Legal Jobs'), ('IT Jobs', 'IT Jobs'), ('R&D Jobs', 'R&D Jobs'), ('Government Jobs', 'Government Jobs'), ('PSU Jobs', 'PSU Jobs'), ('Telecom', 'Telecom'), ('Pharma', 'Pharma'), ('Sales', 'Sales'), ('Analyticsr', 'Analytics'), ('Airline', 'Airline'), ('Teacher', 'Teacher'), ('HR', 'HR'), ('Hotel', 'Hotel')], max_length=100)),
                ('job_titel', models.CharField(max_length=100)),
                ('campany_name', models.CharField(max_length=100)),
                ('sift', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_updates', models.DateTimeField(auto_now_add=True)),
                ('site_link', models.URLField(max_length=60)),
                ('salary_pack', models.FloatField(null=True)),
                ('min_salary', models.FloatField(null=True)),
                ('max_salary', models.FloatField(null=True)),
                ('job_desc', models.TextField()),
                ('joining_facilites', models.CharField(max_length=300)),
                ('notice_period', models.CharField(max_length=50)),
                ('campany_logo', models.ImageField(upload_to='campany_image%y%m%d')),
                ('campany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campany.campnay_profile')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campany.job_type')),
            ],
        ),
    ]
