# Generated by Django 3.1 on 2021-04-27 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0002_auto_20210427_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='campnay_profile',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 10 digits allowed.', regex='^\\+?91?\\d{9,10}$')], verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='jobseeker_profile',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 10 digits allowed.', regex='^\\+?91?\\d{9,10}$')], verbose_name='Phone'),
        ),
    ]
