# Generated by Django 3.1 on 2021-04-28 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0004_auto_20210427_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='add_job_model',
            name='job_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campany.job_category'),
        ),
    ]
