# Generated by Django 3.1 on 2021-04-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0005_auto_20210428_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_job_model',
            old_name='job_titel',
            new_name='job_skills',
        ),
        migrations.AddField(
            model_name='add_job_model',
            name='job_title',
            field=models.CharField(default='ggg', max_length=100),
            preserve_default=False,
        ),
    ]
