# Generated by Django 3.1 on 2021-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0006_auto_20210428_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_job_model',
            name='campany_logo',
        ),
        migrations.RemoveField(
            model_name='add_job_model',
            name='campany_name',
        ),
        migrations.RemoveField(
            model_name='add_job_model',
            name='site_link',
        ),
        migrations.AddField(
            model_name='add_job_model',
            name='job_post_file',
            field=models.FileField(null=True, upload_to='post_file%y%m%d', verbose_name='Document'),
        ),
    ]
