# Generated by Django 3.1 on 2021-04-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0008_add_job_model_ex_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('notic_p', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('gander', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('dob', models.CharField(max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campany.add_job_model')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campany.jobseeker_profile')),
            ],
        ),
    ]
