# Generated by Django 3.1 on 2021-04-28 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0009_applied_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_job',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
