# Generated by Django 3.1 on 2021-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0010_auto_20210428_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
