# Generated by Django 3.1 on 2021-04-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0011_news_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
                ('institute_name', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('passing_year', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobseeker_profile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='jobseeker_profile',
            name='percentage',
        ),
    ]
