# Generated by Django 3.1 on 2021-05-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0013_add_degree_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campnay_profile',
            name='campany_logo',
            field=models.FileField(upload_to='mydocs_resume/'),
        ),
    ]
