# Generated by Django 3.1 on 2021-05-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0016_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker_profile',
            name='mother_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker_profile',
            name='web_site',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_profile',
            name='passing_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker_profile',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
