# Generated by Django 3.1 on 2021-05-03 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0017_auto_20210503_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker_profile',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 10 digits allowed.', regex='^\\+?91?\\d{10}$')], verbose_name='Phone'),
        ),
    ]
