# Generated by Django 3.1 on 2021-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campany', '0018_auto_20210503_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker_profile',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
